/**
 * core/demo-inputs.ts
 *
 * The five bundled examples for DEMO_MODE and for the "try an example" buttons.
 * Pure data — no Node imports — so a client component can import it too.
 *
 * These are the inputs. Their pre-analysed RESULTS live in demo-data.json,
 * generated by scripts/build-demo.ts running the real pipeline over these exact
 * strings. DEMO_MODE looks a submission up by SHA-256 of its trimmed text, so the
 * text here and the text the user submits must match byte-for-byte.
 */

export interface DemoInput {
  id: string;
  label: string;
  text: string;
}

export const DEMO_INPUTS: DemoInput[] = [
  {
    id: "phishing-email",
    label: "Phishing email",
    text: `From: PayPal Service <service@paypa1-verify-secure.com>
Reply-To: recovery-team@mail-secure.ru
Subject: Your account has been limited
Authentication-Results: mx.google.com; spf=fail (sender not permitted); dkim=none; dmarc=fail
Content-Type: text/html

<html><body>
<p>PayPal Security: we detected an unauthorized login to your account, which has now been temporarily limited. You must verify your identity within 24 hours or your account will be permanently suspended.</p>
<p>Confirm your password and card details to restore access: http://paypa1-verify-secure.com/login</p>
<form action="http://paypa1-verify-secure.com/login">
  <input type="text" name="email" placeholder="Email address" />
  <input type="password" name="password" placeholder="Password" />
  <button type="submit">Verify now</button>
</form>
</body></html>`,
  },
  {
    id: "legitimate-email",
    label: "Legitimate email",
    text: `From: GitHub <noreply@github.com>
Reply-To: noreply@github.com
Subject: Your GitHub Sponsors receipt for June
Authentication-Results: mx.google.com; spf=pass; dkim=pass; dmarc=pass

Hi, thanks for supporting open source. This is your monthly receipt for your GitHub Sponsors contributions in June. There is nothing you need to do — we just wanted to send this along for your records. You can view your full billing history any time at https://github.com/settings/billing.`,
  },
  {
    id: "typosquat-url",
    label: "Typosquatted URL",
    text: `https://paypa1-verify-secure.com/account/login`,
  },
  {
    id: "clean-url",
    label: "Clean URL",
    text: `https://google.com`,
  },
  {
    id: "marketing-email",
    label: "Borderline marketing email",
    text: `From: Bloom & Co <news@bloomandco.com>
Reply-To: reply@mailer.sendgrid.net
Subject: Our Summer Sale ends Sunday — 20% off everything
Authentication-Results: mx.google.com; spf=pass; dkim=pass; dmarc=pass

Hi Sarah! Our Summer Sale ends this Sunday at midnight and you do not want to miss it. Take an extra 20% off everything with code SUN20 — these deals disappear the moment the clock strikes twelve, so act now before your favourites sell out for good. Shop the sale here: https://bit.ly/bloom-summer-sale. You're receiving this because you subscribed to Bloom & Co updates. Unsubscribe any time.`,
  },
];
